<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>System.Diagnostics.DiagnosticSource</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="ILLink.Substitutions.xml" />
    <EmbeddedResource Include="ILLink.Substitutions.xml" LogicalName="ILLink.Substitutions.xml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Memory">
      <HintPath>../../../usr/share/dotnet/shared/Microsoft.NETCore.App/10.0.11/System.Memory.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>../../../usr/share/dotnet/shared/Microsoft.NETCore.App/10.0.11/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.CompilerServices.Unsafe">
      <HintPath>../../../usr/share/dotnet/shared/Microsoft.NETCore.App/10.0.11/System.Runtime.CompilerServices.Unsafe.dll</HintPath>
    </Reference>
    <Reference Include="System.Buffers">
      <HintPath>../../../usr/share/dotnet/shared/Microsoft.NETCore.App/10.0.11/System.Buffers.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>